#!/usr/bin/env bash
# ==============================================================================
# terraform/main/run.sh
# ==============================================================================
# Single entrypoint for OpenTofu infrastructure + post‑provision reconciliation.
#
# Terraform creates only the ACA environment (plus storage, ACR, ML workspace,
# Function App, observability, Azure DevOps pipelines). Both Container Apps
# (serving app and training job) and the Event Grid subscription are created
# by this script via Azure CLI after the environment is fully provisioned.
# This avoids the ARM "Operation expired" timeout on student subscriptions.
#
# Local development (az login first):
#   export TF_BACKEND_AUTH_MODE=cli
#   bash src/terraform/main/run.sh --plan    --env staging
#   bash src/terraform/main/run.sh --create  --env staging
#   bash src/terraform/main/run.sh --destroy --env staging --yes-delete
#
# CI/CD (Azure DevOps with OIDC service connection):
#   The pipeline exports ARM_CLIENT_ID, ARM_OIDC_TOKEN, ARM_TENANT_ID,
#   ARM_SUBSCRIPTION_ID, and sets TF_BACKEND_AUTH_MODE=oidc by default.
#   bash src/terraform/main/run.sh --plan    --env staging
#   bash src/terraform/main/run.sh --refresh --env staging
#   bash src/terraform/main/run.sh --create  --env staging --skip-aca
#   bash src/terraform/main/run.sh --create  --env staging
# ==============================================================================

set -euo pipefail
IFS=$'\n\t'

# Always run from the script's own directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
cd "$SCRIPT_DIR" || { echo "ERROR: cannot cd to $SCRIPT_DIR" >&2; exit 1; }

# Generated by bootstrap.sh – contains backend storage config
BOOTSTRAP_ENV_FILE="$SCRIPT_DIR/.bootstrap.generated.env"

log()  { printf '[%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }
fail() { log "ERROR: $*" >&2; exit 1; }
require_cmd() { command -v "$1" >/dev/null 2>&1 || fail "$1 missing"; }

# Strip carriage returns and newlines from Azure CLI output
trim() {
  local s="${1:-}"
  s="${s//$'\r'/}"
  s="${s//$'\n'/}"
  printf '%s' "$s"
}

usage() {
  cat >&2 <<'USAGE'
Usage:
  run.sh --plan    --env <staging|prod> [--skip-aca]
  run.sh --create  --env <staging|prod> [--skip-aca]
  run.sh --destroy --env <staging|prod> --yes-delete
  run.sh --validate --env <staging|prod>
  run.sh --apply-plan <plan-file> --env <staging|prod>
USAGE
  exit 2
}

# ===========================================================================
# 1. Authentication mode (the master switch)
# ===========================================================================
EXPLICIT_AUTH_MODE="${TF_BACKEND_AUTH_MODE:-}"

load_bootstrap_env() {
  if [[ -f "$BOOTSTRAP_ENV_FILE" ]]; then
    source "$BOOTSTRAP_ENV_FILE"
  fi
  if [[ -n "$EXPLICIT_AUTH_MODE" ]]; then
    export TF_BACKEND_AUTH_MODE="$EXPLICIT_AUTH_MODE"
  fi
}

# ===========================================================================
# 2. Install OpenTofu if missing
# ===========================================================================
install_tofu_if_needed() {
  if command -v tofu >/dev/null 2>&1; then return 0; fi
  require_cmd curl; require_cmd unzip
  local v="${TOFU_VERSION:-1.12.4}"
  local tmp_zip="$(mktemp)" tmp_dir="$(mktemp -d)"
  curl -fsSL -o "$tmp_zip" \
    "https://github.com/opentofu/opentofu/releases/download/v${v}/tofu_${v}_linux_amd64.zip"
  unzip -o "$tmp_zip" -d "$tmp_dir" >/dev/null
  mkdir -p "$HOME/bin"
  install -m 0755 "$tmp_dir/tofu" "$HOME/bin/tofu"
  export PATH="$HOME/bin:$PATH"
  rm -rf "$tmp_zip" "$tmp_dir"
}

# ===========================================================================
# 3. Azure context – subscription & tenant
# ===========================================================================
resolve_azure_context() {
  require_cmd az

  TF_VAR_subscription_id="${TF_VAR_subscription_id:-$(az account show --query id -o tsv)}"
  TF_VAR_tenant_id="${TF_VAR_tenant_id:-$(az account show --query tenantId -o tsv)}"

  TF_VAR_subscription_id="$(trim "$TF_VAR_subscription_id")"
  TF_VAR_tenant_id="$(trim "$TF_VAR_tenant_id")"

  [[ -n "$TF_VAR_subscription_id" ]] || fail "unable to resolve Azure subscription"
  [[ -n "$TF_VAR_tenant_id" ]]       || fail "unable to resolve Azure tenant"

  # Always export for Terraform (both CLI and OIDC modes need these)
  export TF_VAR_subscription_id TF_VAR_tenant_id

  # Also make them available as plain variables for the script
  AZURE_SUBSCRIPTION_ID="$TF_VAR_subscription_id"
  export AZURE_SUBSCRIPTION_ID
}

# ===========================================================================
# 4. Backend configuration for Terraform state
# ===========================================================================
choose_auth_mode() {
  if [[ -n "${TF_BACKEND_AUTH_MODE:-}" ]]; then
    case "$TF_BACKEND_AUTH_MODE" in
      oidc|cli|access_key) AUTH_MODE="$TF_BACKEND_AUTH_MODE" ;;
      *) fail "unsupported TF_BACKEND_AUTH_MODE: $TF_BACKEND_AUTH_MODE" ;;
    esac
    return
  fi
  if [[ -n "${ARM_ACCESS_KEY:-}" ]]; then AUTH_MODE="access_key"
  elif [[ -n "${ARM_OIDC_TOKEN:-}" ]]; then AUTH_MODE="oidc"
  else AUTH_MODE="cli"
  fi
}

compute_defaults() {
  local s="${SUBSCRIPTION_SUFFIX:-${AZURE_SUBSCRIPTION_ID: -6}}"
  TF_BACKEND_RESOURCE_GROUP="${TF_BACKEND_RESOURCE_GROUP:-rg-sm-state-${s}}"
  TF_BACKEND_STORAGE_ACCOUNT="${TF_BACKEND_STORAGE_ACCOUNT:-smstatesa${s}}"
  TF_BACKEND_CONTAINER="${TF_BACKEND_CONTAINER:-tfbackend}"
  TF_BACKEND_KEY_PREFIX="${TF_BACKEND_KEY_PREFIX:-main/terraform}"
}

build_backend_config() {
  local cfg="$(mktemp)"
  case "$AUTH_MODE" in
    access_key)
      cat >"$cfg" <<EOF
resource_group_name  = "$TF_BACKEND_RESOURCE_GROUP"
storage_account_name = "$TF_BACKEND_STORAGE_ACCOUNT"
container_name       = "$TF_BACKEND_CONTAINER"
key                  = "$TF_BACKEND_KEY"
access_key           = "$ARM_ACCESS_KEY"
EOF
      ;;
    oidc)
      cat >"$cfg" <<EOF
resource_group_name  = "$TF_BACKEND_RESOURCE_GROUP"
storage_account_name = "$TF_BACKEND_STORAGE_ACCOUNT"
container_name       = "$TF_BACKEND_CONTAINER"
key                  = "$TF_BACKEND_KEY"
use_azuread_auth     = true
subscription_id      = "$AZURE_SUBSCRIPTION_ID"
tenant_id            = "$TF_VAR_tenant_id"
client_id            = "${ARM_CLIENT_ID:-}"
use_oidc             = true
EOF
      ;;
    cli)
      # When using CLI auth, do NOT pass subscription_id/tenant_id
      cat >"$cfg" <<EOF
resource_group_name  = "$TF_BACKEND_RESOURCE_GROUP"
storage_account_name = "$TF_BACKEND_STORAGE_ACCOUNT"
container_name       = "$TF_BACKEND_CONTAINER"
key                  = "$TF_BACKEND_KEY"
EOF
      ;;
    *) fail "unsupported auth mode: $AUTH_MODE" ;;
  esac
  printf '%s' "$cfg"
}

init_backend() {
  local cfg="$(build_backend_config)"
  tofu init -reconfigure -input=false -upgrade -backend-config="$cfg"
  rm -f "$cfg"
}

# ===========================================================================
# 5. Core Terraform operations
# ===========================================================================
ensure_plan_dir() { mkdir -p "$PLAN_DIR"; }

prepare_stack() {
  tofu fmt -recursive
  init_backend
  tofu validate -no-color
}

run_plan() {
  ensure_plan_dir
  rm -f "$PLAN_FILE"
  prepare_stack
  tofu plan -input=false -lock-timeout=5m -var-file="$VAR_FILE" -out="$PLAN_FILE"
}

run_apply_plan() {
  [[ -f "$PLAN_FILE_INPUT" ]] || fail "plan file not found: $PLAN_FILE_INPUT"
  init_backend
  az account get-access-token --resource https://management.azure.com >/dev/null 2>&1 || true
  tofu apply -input=false -lock-timeout=5m -auto-approve "$PLAN_FILE_INPUT"
}

# ===========================================================================
# 6. Derived names (same deterministic convention as locals.tf)
# ===========================================================================
derive_names() {
  local s="${AZURE_SUBSCRIPTION_ID: -6}"
  local p="sm"
  local e
  case "$ENVIRONMENT" in
    staging) e="stg" ;;
    prod)    e="prod" ;;
    *)       fail "unknown environment: $ENVIRONMENT" ;;
  esac

  RG_NAME="rg-${p}-artifacts-${e}"
  STORAGE_ACCOUNT_NAME="${p}${e}artifacts${s}"
  ACR_NAME="acr${p}${e}${s}"
  ACR_SERVER="${ACR_NAME}.azurecr.io"
  SERVE_APP_NAME="aca-serve-${e}"
  TRAIN_JOB_NAME="acaj-train-${e}"
  ENV_NAME="acae-${p}-${e}"
  FUNCTION_APP_NAME="func-blob-trigger-${e}"
}

# ===========================================================================
# 7. Safely read a Terraform output
# ===========================================================================
get_tofu_output() { tofu output -raw "$1" 2>/dev/null || true; }

# ===========================================================================
# 8. Idempotent role assignment
# ===========================================================================
ensure_role_assignment() {
  local oid="$1" role="$2" scope="$3"
  local cnt
  cnt="$(az role assignment list \
    --assignee-object-id "$oid" --scope "$scope" \
    --query "[?roleDefinitionName=='${role}'] | length(@)" -o tsv 2>/dev/null || echo 0)"
  if [[ "${cnt:-0}" == "0" ]]; then
    az role assignment create \
      --assignee-object-id "$oid" --assignee-principal-type ServicePrincipal \
      --role "$role" --scope "$scope" --output none
    log "Assigned ${role} to ${oid}"
  else
    log "Role ${role} already assigned"
  fi
}

# ===========================================================================
# 9. Serving app (CLI – no Terraform timeouts)
# ===========================================================================
create_serving_app() {
  derive_names
  local app="$SERVE_APP_NAME" rg="$RG_NAME" env="$ENV_NAME"
  local image="${SERVE_IMAGE:-mcr.microsoft.com/azuredocs/containerapps-helloworld:latest}"
  local port="${SERVE_PORT:-80}"
  local conn_str="${APPLICATIONINSIGHTS_CONNECTION_STRING:-$(get_tofu_output application_insights_connection_string)}"

  [[ -n "$ML_WORKSPACE_ID" ]] || fail "missing ML_WORKSPACE_ID"
  [[ -n "$MLFLOW_TRACKING_URI" ]] || fail "missing MLFLOW_TRACKING_URI"
  [[ -n "$conn_str" ]] || fail "missing Application Insights connection string"

  log "Creating serving app ${app}"

  az containerapp create \
    --name "$app" \
    --resource-group "$rg" \
    --environment "$env" \
    --image "$image" \
    --target-port "$port" \
    --ingress external \
    --transport http \
    --revisions-mode multiple \
    --min-replicas 0 \
    --max-replicas 10 \
    --cpu 0.5 \
    --memory 1.0Gi \
    --system-assigned \
    --registry-server "$ACR_SERVER" \
    --registry-identity system \
    --env-vars \
      MODE=serve \
      PORT=80 \
      MLFLOW_TRACKING_URI="$MLFLOW_TRACKING_URI" \
      AZUREML_WORKSPACE_ID="$ML_WORKSPACE_ID" \
      APPLICATIONINSIGHTS_CONNECTION_STRING="$conn_str" \
    --output none

  # Poll until Succeeded (up to 30 minutes)
  local max=1800 el=0 iv=30 st
  while (( el < max )); do
    st="$(az containerapp show --name "$app" --resource-group "$rg" \
      --query "properties.provisioningState" -o tsv 2>/dev/null || true)"
    case "$st" in
      Succeeded) log "Serving app ${app} ready"; return 0 ;;
      Failed)
        log "Serving app ${app} failed – recreating"
        az containerapp delete --name "$app" --resource-group "$rg" --yes --output none 2>/dev/null || true
        sleep 10
        az containerapp create \
          --name "$app" --resource-group "$rg" --environment "$env" \
          --image "$image" --target-port "$port" --ingress external --transport http \
          --revisions-mode multiple --min-replicas 0 --max-replicas 10 \
          --cpu 0.5 --memory 1.0Gi --system-assigned \
          --registry-server "$ACR_SERVER" --registry-identity system \
          --env-vars MODE=serve PORT=80 MLFLOW_TRACKING_URI="$MLFLOW_TRACKING_URI" \
            AZUREML_WORKSPACE_ID="$ML_WORKSPACE_ID" \
            APPLICATIONINSIGHTS_CONNECTION_STRING="$conn_str" \
          --output none
        ;;
      *) log "Serving app state: ${st} (${el}s)" ;;
    esac
    sleep "$iv"; el=$((el+iv))
  done
  fail "Timeout waiting for serving app ${app}"
}

# ===========================================================================
# 10. Training job (CLI – no Terraform timeouts)
# ===========================================================================
job_provisioning_state() {
  az containerapp job show --name "$1" --resource-group "$2" \
    --query "properties.provisioningState" -o tsv 2>/dev/null || true
}

assign_training_job_rbac() {
  derive_names
  local oid
  oid="$(az containerapp job show --name "$TRAIN_JOB_NAME" --resource-group "$RG_NAME" \
    --query "identity.principalId" -o tsv 2>/dev/null || true)"
  [[ -n "$oid" ]] || fail "Unable to read job identity"

  local store="/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${RG_NAME}/providers/Microsoft.Storage/storageAccounts/${STORAGE_ACCOUNT_NAME}"
  local acr="/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${RG_NAME}/providers/Microsoft.ContainerRegistry/registries/${ACR_NAME}"
  local ml="${ML_WORKSPACE_ID}"

  ensure_role_assignment "$oid" "Storage Blob Data Contributor" "$store"
  ensure_role_assignment "$oid" "AcrPull" "$acr"
  ensure_role_assignment "$oid" "AzureML Data Scientist" "$ml"
}

assign_function_operator_role() {
  derive_names
  local oid
  oid="$(az functionapp identity show --name "$FUNCTION_APP_NAME" --resource-group "$RG_NAME" \
    --query "principalId" -o tsv 2>/dev/null || true)"
  [[ -n "$oid" ]] || fail "Unable to read Function identity"

  local job_scope="/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${RG_NAME}/providers/Microsoft.App/jobs/${TRAIN_JOB_NAME}"
  ensure_role_assignment "$oid" "Container Apps Jobs Operator" "$job_scope"
}

wait_for_job_ready() {
  derive_names
  local max="${1:-1800}" iv="${2:-30}" el=0 st
  while (( el <= max )); do
    st="$(job_provisioning_state "$TRAIN_JOB_NAME" "$RG_NAME")"
    case "$st" in
      Succeeded) log "Job ready"; return 0 ;;
      Failed|Canceled) return 1 ;;
      Deleting) ;;
      *) log "Job state: ${st:-Unknown} (${el}s)" ;;
    esac
    sleep "$iv"; el=$((el+iv))
  done
  fail "Timeout waiting for job"
}

create_training_job() {
  derive_names

  ML_WORKSPACE_ID="${ML_WORKSPACE_ID:-$(get_tofu_output ml_workspace_id)}"
  local mlflow="${MLFLOW_TRACKING_URI:-$(get_tofu_output mlflow_tracking_uri)}"
  [[ -n "$ML_WORKSPACE_ID" ]] || fail "Missing ML_WORKSPACE_ID"
  [[ -n "$mlflow" ]]          || fail "Missing MLFLOW_TRACKING_URI"

  local image="${TRAIN_IMAGE:-busybox:1.36.1}"
  local cpu="${TRAIN_CPU:-2}"
  local mem="${TRAIN_MEMORY:-4.0Gi}"
  local to="${TRAIN_TIMEOUT:-1800}"
  local retries="${TRAIN_RETRIES:-1}"
  local par="${TRAIN_PARALLELISM:-1}"
  local cc="${TRAIN_COMPLETION_COUNT:-1}"

  log "Creating training job ${TRAIN_JOB_NAME}"

  az containerapp job create \
    --name "$TRAIN_JOB_NAME" --resource-group "$RG_NAME" \
    --environment "$ENV_NAME" --trigger-type Manual \
    --image "$image" --cpu "$cpu" --memory "$mem" \
    --replica-timeout "$to" --replica-retry-limit "$retries" \
    --replica-completion-count "$cc" --parallelism "$par" \
    --mi-system-assigned \
    --registry-server "$ACR_SERVER" --registry-identity system \
    --env-vars \
      MODE=train \
      RAW_CONTAINER_NAME=raw \
      CLEAN_CONTAINER_NAME=clean \
      CHECKPOINT_CONTAINER_NAME=checkpoints \
      AZURE_STORAGE_ACCOUNT_NAME="$STORAGE_ACCOUNT_NAME" \
      MLFLOW_TRACKING_URI="$mlflow" \
      AZUREML_WORKSPACE_ID="$ML_WORKSPACE_ID" \
      INPUT_BLOB_NAME="" \
    --output none

  wait_for_job_ready 1800 30
  assign_training_job_rbac
  log "Training job ready"
}

ensure_job_provisioned() {
  derive_names
  local st
  st="$(job_provisioning_state "$TRAIN_JOB_NAME" "$RG_NAME")"
  case "$st" in
    Succeeded)   log "Job already healthy"; assign_training_job_rbac ;;
    InProgress)  log "Job provisioning – waiting"; wait_for_job_ready 1800 30; assign_training_job_rbac ;;
    Failed|Canceled|Deleting)
      log "Job ${st} – recreating"
      az containerapp job delete --name "$TRAIN_JOB_NAME" --resource-group "$RG_NAME" --yes --output none 2>/dev/null || true
      sleep 10
      create_training_job
      ;;
    *)           create_training_job ;;
  esac
}

# ===========================================================================
# 11. Event Grid subscription (after Function code is deployed)
# ===========================================================================
create_event_grid_subscription() {
  derive_names

  local function_app_name="$FUNCTION_APP_NAME"
  local rg="$RG_NAME"
  local storage_account_id="/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${rg}/providers/Microsoft.Storage/storageAccounts/${STORAGE_ACCOUNT_NAME}"
  local subscription_name="func-blob-trigger-${ENVIRONMENT}-blob-created"
  local blobs_key=""
  local attempt=1
  local max_attempts=30

  # Wait for the blobs_extension system key (only available after host indexes the trigger)
  while [[ "$attempt" -le "$max_attempts" ]]; do
    blobs_key="$(az functionapp keys list \
      --name "$function_app_name" --resource-group "$rg" \
      --query "systemKeys.blobs_extension" -o tsv 2>/dev/null || true)"
    [[ -n "$blobs_key" ]] && break
    log "Waiting for blobs_extension system key on ${function_app_name} (${attempt}/${max_attempts})"
    sleep 10
    attempt=$((attempt + 1))
  done
  [[ -n "$blobs_key" ]] || fail "Unable to retrieve blobs_extension system key for ${function_app_name}"

  local webhook_url="https://${function_app_name}.azurewebsites.net/runtime/webhooks/blobs?functionName=Host.Functions.blob_created&code=${blobs_key}"

  # Delete existing subscription if present (idempotent)
  if az eventgrid event-subscription show --name "$subscription_name" --source-resource-id "$storage_account_id" >/dev/null 2>&1; then
    log "Deleting existing Event Grid subscription ${subscription_name}"
    az eventgrid event-subscription delete --name "$subscription_name" --source-resource-id "$storage_account_id" --only-show-errors >/dev/null
  fi

  log "Creating Event Grid subscription ${subscription_name}"
  az eventgrid event-subscription create \
    --name "$subscription_name" \
    --source-resource-id "$storage_account_id" \
    --included-event-types Microsoft.Storage.BlobCreated \
    --subject-begins-with "/blobServices/default/containers/raw/blobs/monthly/" \
    --subject-ends-with ".parquet" \
    --endpoint-type webhook \
    --endpoint "$webhook_url" \
    --only-show-errors -o none

  log "Event Grid subscription created"
}

# ===========================================================================
# 12. Destroy
# ===========================================================================
nuclear_destroy() {
  log "starting nuclear destroy for $ENVIRONMENT"
  derive_names

  local sub="${AZURE_SUBSCRIPTION_ID: -6}"
  local loc="eastus2"
  local env_abbr
  case "$ENVIRONMENT" in
    staging) env_abbr="stg" ;;
    prod)    env_abbr="prod" ;;
    *)       fail "unknown environment: $ENVIRONMENT" ;;
  esac

  log "breaking state lock if present"
  az storage blob lease break \
    --blob-name "${TF_BACKEND_KEY_PREFIX}/${ENVIRONMENT}.tfstate" \
    --container-name "$TF_BACKEND_CONTAINER" --account-name "$TF_BACKEND_STORAGE_ACCOUNT" \
    --auth-mode login 2>/dev/null || true

  log "deleting resource group: ${RG_NAME}"
  if az group show -n "$RG_NAME" &>/dev/null; then
    az group delete -n "$RG_NAME" --yes
    while az group show -n "$RG_NAME" &>/dev/null; do sleep 15; done
  fi

  local kv="kv-sm${env_abbr}ml${sub}"
  local ml="mlw-sm-${env_abbr}"
  log "purging soft-deleted Key Vault ${kv} and ML workspace ${ml}"
  az keyvault purge -n "$kv" 2>/dev/null || true
  az rest --method delete \
    --url "https://management.azure.com/subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.MachineLearningServices/locations/${loc}/deletedWorkspaces/${ml}?api-version=2024-10-01" \
    2>/dev/null || true

  local sk="${TF_BACKEND_KEY_PREFIX}/${ENVIRONMENT}.tfstate"
  log "deleting state blob ${sk}"
  local uid; uid=$(az ad signed-in-user show --query id -o tsv 2>/dev/null) || true
  if [[ -n "$uid" ]]; then
    az role assignment create --assignee "$uid" --role "Storage Blob Data Contributor" \
      --scope "/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${TF_BACKEND_RESOURCE_GROUP}/providers/Microsoft.Storage/storageAccounts/${TF_BACKEND_STORAGE_ACCOUNT}" \
      2>/dev/null || true
  fi
  az storage blob delete --account-name "$TF_BACKEND_STORAGE_ACCOUNT" --container-name "$TF_BACKEND_CONTAINER" \
    --name "$sk" --auth-mode login 2>/dev/null || true
  log "nuclear destroy complete"
}

# ===========================================================================
# 13. Function code deployment
# ===========================================================================
deploy_function_code() {
  derive_names
  local root="$(cd "$SCRIPT_DIR/../../.." && pwd -P)"
  local src="${root}/src/workloads/blob_trigger"
  [[ -f "${src}/host.json" ]] || fail "host.json not found in ${src}"

  log "Deploying function code to ${FUNCTION_APP_NAME}"

  if ! command -v func >/dev/null 2>&1; then
    log "Installing Azure Functions Core Tools..."
    curl -fsSL https://packages.microsoft.com/keys/microsoft.asc \
      | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg >/dev/null 2>&1
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-noble-prod noble main" \
      | sudo tee /etc/apt/sources.list.d/microsoft-prod.list >/dev/null
    sudo apt-get update -qq
    sudo apt-get install -y -qq azure-functions-core-tools-4=4.12.1-1
  fi

  ( cd "$src" && func azure functionapp publish "$FUNCTION_APP_NAME" --python --build remote ) \
    || fail "Function deploy failed"
  log "Function code deployed"
}

# ===========================================================================
# 14. Argument parsing
# ===========================================================================
MODE=""; ENVIRONMENT=""; PLAN_FILE_INPUT=""; YES_DELETE=false; SKIP_ACA=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --plan|--create|--validate|--destroy|--refresh) MODE="$1"; shift ;;
    --apply-plan) MODE="--apply-plan"; shift; PLAN_FILE_INPUT="${1:-}"; [[ -n "$PLAN_FILE_INPUT" ]] || usage; shift ;;
    --env) ENVIRONMENT="${2:-}"; [[ -n "$ENVIRONMENT" ]] || usage; shift 2 ;;
    --yes-delete) YES_DELETE=true; shift ;;
    --skip-aca) SKIP_ACA=true; shift ;;
    *) usage ;;
  esac
done
[[ -n "$MODE" ]] || usage
if [[ "$MODE" != "--validate" && -z "$ENVIRONMENT" ]]; then usage; fi
require_cmd sha256sum python3 curl unzip

# ===========================================================================
# 15. Auto‑derive Azure DevOps variables
# ===========================================================================
resolve_git_remote() {
  command -v git >/dev/null 2>&1 || return 1
  local u="$(git -C "$SCRIPT_DIR" remote get-url origin 2>/dev/null || true)"
  [[ -n "$u" ]] || return 1
  case "$u" in
    https://github.com/*) u="${u#https://github.com/}" ;;
    git@github.com:*)     u="${u#git@github.com:}" ;;
    ssh://git@github.com/*) u="${u#ssh://git@github.com/}" ;;
    *) return 1 ;;
  esac
  u="${u%.git}"
  GIT_OWNER="${u%%/*}"; GIT_REPO="${u##*/}"
  [[ -n "$GIT_OWNER" && -n "$GIT_REPO" && "$GIT_OWNER" != "$GIT_REPO" ]]
}

resolve_ado_vars() {
  local s="${AZURE_SUBSCRIPTION_ID: -6}"
  export TF_VAR_ado_client_id="${TF_VAR_ado_client_id:-${ARM_CLIENT_ID:-}}"
  export TF_VAR_ado_project_name="${TF_VAR_ado_project_name:-azdo-bootstrap-${s}}"
  export TF_VAR_ado_github_service_connection_name="${TF_VAR_ado_github_service_connection_name:-github-pat}"
  export TF_VAR_ado_azure_service_connection_name="${TF_VAR_ado_azure_service_connection_name:-azdo-oidc-ci}"
  if resolve_git_remote; then
    export TF_VAR_github_owner="${TF_VAR_github_owner:-$GIT_OWNER}"
    export TF_VAR_github_repo="${TF_VAR_github_repo:-$GIT_REPO}"
  else
    log "WARNING: unable to resolve git remote"
  fi
  export TF_VAR_state_rg_name="${TF_VAR_state_rg_name:-$TF_BACKEND_RESOURCE_GROUP}"
  export TF_VAR_state_storage_account_name="${TF_VAR_state_storage_account_name:-$TF_BACKEND_STORAGE_ACCOUNT}"
  export TF_VAR_state_container_name="${TF_VAR_state_container_name:-$TF_BACKEND_CONTAINER}"
}

# ===========================================================================
# 16. Execution
# ===========================================================================
load_bootstrap_env; resolve_azure_context; choose_auth_mode; install_tofu_if_needed
compute_defaults; resolve_ado_vars

# Map Azure DevOps credentials if present
if [[ -n "${TF_VAR_AZDO_ORG_SERVICE_URL:-}" ]]; then
  export AZDO_ORG_SERVICE_URL="$TF_VAR_AZDO_ORG_SERVICE_URL"
elif [[ -n "${TF_VAR_ado_org_service_url:-}" ]]; then
  export AZDO_ORG_SERVICE_URL="$TF_VAR_ado_org_service_url"
fi
if [[ -n "${TF_VAR_AZDO_PERSONAL_ACCESS_TOKEN:-}" ]]; then
  export AZDO_PERSONAL_ACCESS_TOKEN="$TF_VAR_AZDO_PERSONAL_ACCESS_TOKEN"
elif [[ -n "${TF_VAR_ado_personal_access_token:-}" ]]; then
  export AZDO_PERSONAL_ACCESS_TOKEN="$TF_VAR_ado_personal_access_token"
fi

TF_BACKEND_KEY="${TF_BACKEND_KEY:-${TF_BACKEND_KEY_PREFIX}/${ENVIRONMENT}.tfstate}"
PLAN_DIR="$SCRIPT_DIR/.plans/$ENVIRONMENT"
PLAN_FILE="$PLAN_DIR/plan.tfplan"
VAR_FILE="$SCRIPT_DIR/environments/${ENVIRONMENT}.tfvars"

case "$MODE" in
  --validate) prepare_stack ;;
    # --------------------------------------------------------------------------
  # --refresh: refresh the Terraform state from live Azure resources.
  # Used by the CI pipeline before planning to heal state drift from
  # previous targeted applies.
  # --------------------------------------------------------------------------
  --refresh)
    install_tofu_if_needed
    init_backend
    tofu apply -refresh-only -auto-approve -var-file="$VAR_FILE"
    log "state refreshed from Azure"
    ;;
  --plan)
    [[ -f "$VAR_FILE" ]] || fail "variable file not found: $VAR_FILE"
    run_plan
    log "plan written to $PLAN_FILE"
    ;;
  --create)
    [[ -f "$VAR_FILE" ]] || fail "variable file not found: $VAR_FILE"
    run_plan
    az account get-access-token --resource https://management.azure.com >/dev/null 2>&1 || true

    if $SKIP_ACA; then
      log "deleting CLI-managed Container Apps before infrastructure apply"
      derive_names
      az containerapp delete \
        --name "$SERVE_APP_NAME" --resource-group "$RG_NAME" \
        --yes --output none 2>/dev/null || true
      az containerapp job delete \
        --name "$TRAIN_JOB_NAME" --resource-group "$RG_NAME" \
        --yes --output none 2>/dev/null || true
      sleep 10

      log "applying infrastructure only (skipping Container Apps)"
      tofu apply -input=false -lock-timeout=5m -auto-approve \
        -target=module.state \
        -target=module.observability \
        -target=module.ml_workspace \
        -target=module.function \
        -target=module.azure_devops \
        "$PLAN_FILE"
    else
      tofu apply -input=false -lock-timeout=5m -auto-approve "$PLAN_FILE" || {
        log "Terraform apply had errors – continuing with CLI healing"
      }

      ML_WORKSPACE_ID="$(get_tofu_output ml_workspace_id)"
      MLFLOW_TRACKING_URI="$(get_tofu_output mlflow_tracking_uri)"
      APPLICATIONINSIGHTS_CONNECTION_STRING="$(get_tofu_output application_insights_connection_string)"

      log "creating serving app"
      create_serving_app

      log "ensuring training job exists"
      ensure_job_provisioned

      log "assigning Function operator role"
      assign_function_operator_role

      log "deploying function code"
      deploy_function_code

      log "creating Event Grid subscription"
      create_event_grid_subscription
    fi
    ;;
  --apply-plan) run_apply_plan ;;
  --destroy)
    $YES_DELETE || fail "--yes-delete required"
    [[ -f "$VAR_FILE" ]] || fail "variable file not found: $VAR_FILE"

    log "deleting CLI-managed Container Apps"
    derive_names
    az containerapp delete \
      --name "$SERVE_APP_NAME" \
      --resource-group "$RG_NAME" \
      --yes --output none 2>/dev/null || true
    az containerapp job delete \
      --name "$TRAIN_JOB_NAME" \
      --resource-group "$RG_NAME" \
      --yes --output none 2>/dev/null || true
    sleep 10

    nuclear_destroy
    ;;
  *) usage ;;
esac
