{{- if and (eq .Values.auth.mode "WorkloadIdentity") .Values.auth.workloadIdentity.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.auth.workloadIdentity.serviceAccountName }}
  namespace: {{ .Values.auth.workloadIdentity.serviceAccountNamespace }}
  labels:
    {{- include "externalsecrets.labels" . | nindent 4 }}
  {{- with .Values.auth.workloadIdentity.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
